# see README.md for details how to run databases in docker
javax:
  sql:
    DataSource:
      db:
        datasource:
          url: "postgresql://localhost:5432/ecommerce_db"
          username: "postgres"
          password: "postgres"
          initializationFailTimeout: -1
          connectionTimeout: 2000
          helidon:
            pool-metrics:
              enabled: true
              # name prefix defaults to "db.pool." - if you have more than one client within a JVM, you may want to distinguish between them
              name-prefix: "hikari."
        services:
          tracing:
            - enabled: true
          metrics:
            - type: TIMER
        health-check:
          type: "query"
          statementName: "health-check"